config/routes.rb
IbekSystems::Application.routes.draw do

  root :to => 'payments#index'

  resources :payments

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  validates :credit_card_number, :uniqueness => true
  validate :verify_card_number

  attr_accessible :credit_card_number

  def verify_card_number
    if self[:credit_card_number] !~ /^[0-9]{16}$/
      errors.add(:credit_card_number, 'Input data doesn\'t match required format!')
    else
      dst = self[:credit_card_number].split(//).each_with_index.map{ |el, i|
        if i%2==0 then (r = el.to_i*2) > 9 ? (r - 9) : (r) else el.to_i end
      }
      #ruby 1.9 way
      errors.add(:credit_card_number, 'Wrong') if dst.inject(:+) % 10 != 0
      #or you can use dst.inject{ |result, el| result + el} instead of dst.inject(:+)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def index
    @payments = Payment.all
  end

  def create
    @payment = Payment.new(params[:payment])

    if @payment.save
      redirect_to payments_path
    else
      render 'new'
    end
  end

  def new
    @payment = Payment.new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/verify_card_helper.rb
module VerifyCardHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IbekSystems</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/payments/_form.html.erb
<br/><b>4244671320161090</b>
<%= form_for @payment do |f| %>
    <% if @payment.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @payment.errors.full_messages.each do |e| %>
                <li><%= e %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.label :credit_card_number %>
    <%= f.text_field :credit_card_number %>
    <%= f.submit 'Verify!' %>
<% end %>

app/views/payments/index.html.erb
<ul>
  <% @payments.each do |p| %>
      <li><%= p.credit_card_number  %></li>
  <% end %>
</ul>

<%= link_to 'new', new_payment_path %>

app/views/payments/new.html.erb
<%= render :partial => 'payments/form', :locals => {:payment => @payment} %>